// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB91_KX3u7jPNZYr4X4Zs0_xJQ7xud3vns',
    appId: '1:488432078829:web:995dce0784961d1fdaa1e4',
    messagingSenderId: '488432078829',
    projectId: 'testingfirebase-15982',
    authDomain: 'testingfirebase-15982.firebaseapp.com',
    storageBucket: 'testingfirebase-15982.appspot.com',
    measurementId: 'G-SGRXCMBZQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPzGoQJkcAdzyrZi-Y25ABCRuNDLV1cUs',
    appId: '1:488432078829:android:3dca8582023dd052daa1e4',
    messagingSenderId: '488432078829',
    projectId: 'testingfirebase-15982',
    storageBucket: 'testingfirebase-15982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ReNTngxSFRpdocDohwLS8TqYoFsYREM',
    appId: '1:488432078829:ios:8406a17774efc29bdaa1e4',
    messagingSenderId: '488432078829',
    projectId: 'testingfirebase-15982',
    storageBucket: 'testingfirebase-15982.appspot.com',
    iosBundleId: 'com.example.loginAssignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ReNTngxSFRpdocDohwLS8TqYoFsYREM',
    appId: '1:488432078829:ios:e7ce472522caa691daa1e4',
    messagingSenderId: '488432078829',
    projectId: 'testingfirebase-15982',
    storageBucket: 'testingfirebase-15982.appspot.com',
    iosBundleId: 'com.example.loginAssignment2.RunnerTests',
  );
}
